### ISSUE TITLE
mqtt data working but availability is always reporting offline state

### ISSUE THREAD

**Issue by slashx57** [dotvav/aasivak#13]
Hello,
i can see the entity in HA and see topics on MQTT but unable to set mode because of the availability still at offline.
i'm also unable to see logs and don't now why

**Comment by dotvav** [comment]
Are you seeing the unit as offline in HA, in the MQTT topics?

The logs are being rendered in the standard output of the python script. You may want to check the system logs. I am running it as a systemd service on a Ubuntu box and am checking the logs with `sudo journalctl -u aasivak -e`. Please share some anonymized log.

**Comment by slashx57** [comment]
I discovered that my unit is disconnected from wifi and it's for instance impossible to do the pairing operation.
Did you encountered this kind of issue ?

**Comment by dotvav** [comment]
It's happened a couple time, and I had to redo the pairing operation.
