### ISSUE TITLE
Integration for other systems

### ISSUE THREAD

**Issue by eldarmusin** [dotvav/aasivak#15]
Hi @dotvav,

I would like to contribute to the project, but do not really know where to start.
I have a freshly installed heat pump, and looking to make it smarter.

Could we have a chat together about small guideline to the API?

Merci d'avance.

**Comment by dotvav** [comment]
Hi @eldarmusin I am currently not putting a lot of time into this. I am sharing this component as is and I am happy to take suggestions, but I don't really have a long term plan 😆.

**Comment by eldarmusin** [comment]
How have you performed a reverse engineering?
Which device do you use to listen to H-Link?

**Comment by dotvav** [comment]
I have tested 2 things that give the same results:
* watch the network logs in Chrome while using https://hi-kumo.com/
* intercepting the android app's traffic by adding an mitmproxy instance in my phone's wifi setup

I haven't found a way to run an mitm attack between the hikumo device/gateway and its server as the traffic seems to be encrypted and verified with some internal SSL certificate. I haven't dared yet breaking the device open to find if some uart ports are usable to dump the firmware or the SSL keys...

**Comment by eldarmusin** [comment]
Wow, ok nice. Thanks for tips.

To connect to hi-kumo, you need an electronic device to connect to Hitachi system. Which one do you have?

**Comment by dotvav** [comment]
I have a few "SPX-WFG01" in my home.

**Comment by eldarmusin** [comment]
Oh, they are not compliant with my yutaki :(
